<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CryptoTrading.Application\CryptoTrading.Application.csproj" />
    <ProjectReference Include="..\CryptoTrading.Domain\CryptoTrading.Domain.csproj" />
    <ProjectReference Include="..\CryptoTrading.Infrastructure\CryptoTrading.Infrastructure.csproj" />
  </ItemGroup>

</Project>
